[package]
name = "rustvmm"
version = "0.1.0"
edition = "2021"

[dependencies]
vmm = { path = "third_party/vmm-reference/src/vmm" }

[patch.crates-io]
event-manager = { path = "third_party/event-manager" }
linux-loader = { path = "third_party/linux-loader" }
kvm-ioctls = { path = "third_party/kvm-ioctls" }
vm-memory = { path = "third_party/vm-memory" }
vmm-sys-util = { path = "vendor/vmm-sys-util" }

[patch."https://github.com/rust-vmm/vm-virtio.git"]
vm-memory = { path = "third_party/vm-memory" }
vmm-sys-util = { path = "vendor/vmm-sys-util" }
